name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '13 3 * * 1' # one week

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt-clippy:
    name: fmt + clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  # Main test matrix
  test:
    name: test ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          # Reduce jobs: only stable on macOS/Windows
          - os: macos-latest
            rust: beta
          - os: macos-latest
            rust: nightly
          - os: windows-latest
            rust: beta
          - os: windows-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose
      - run: cargo test --all-features --verbose
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  # TODO: enable deny
  # Full cargo-deny check (licenses, advisories, bans, sources, duplicates)
  #deny:
    #name: deny
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
      #- uses: dtolnay/rust-toolchain@stable
      #- uses: EmbarkStudios/cargo-deny-action@v2 # runs licenses, advisories, bans, sources, duplicates

  # Audit to check for security vulnerabilities
  # TODO: enable audit
  #audit:
    #name: audit
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
      #- uses: dtolnay/rust-toolchain@stable
      #- run: cargo install cargo-audit
      #- run: cargo audit
